### PR TITLE
Make example runnable via java -jar

### PR DESCRIPTION
**Pull request by Croway**

### CODE REVIEW

**Comment by cunningt** [comment]
I experimented a bunch with this, and I'm not sure of all of the test suite requirements, but I think this may work for testing, with no changes necessary -- the advantage to this approach is that we do not hit the sapidoc/sapjco renaming issue which I hit quite a bit while trying to get this to work in a `java -jar` scenario 

`sh% java -cp target/sap-idoc-destination-spring-boot-3.20.1-SNAPSHOT.jar:./lib/sapidoc3.jar:./lib/sapjco3.jar -Dloader.main=com.redhat.quickstarts.fuse.sap_idoc_destination_spring_boot.Application org.springframework.boot.loader.PropertiesLauncher`

By the same token, this seems like an okay way of getting these quickstarts to work on openshift.       I'll prepare a PR tomorrow, but if we add a classpath file with the contents of 

```
/deployments/sap-idoc-destination-spring-boot-3.20.1-SNAPSHOT.jar:/deployments/lib/sapidoc3.jar:/deployments/lib/sapjco3.jar
```

```
	<profiles>
        <profile>
            <id>openshift</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.eclipse.jkube</groupId>
                        <artifactId>openshift-maven-plugin</artifactId>
                        <version>1.13.1</version>
		       <configuration>
                            <resources>
                                <controller>
                                    <env>
                                        <AB_PROMETHEUS_OFF>true</AB_PROMETHEUS_OFF>
                                        <AB_JOLOKIA_OFF>true</AB_JOLOKIA_OFF>
                                        <AB_ENABLED>false</AB_ENABLED>
                                        <JAVA_MAIN_CLASS>org.springframework.boot.loader.PropertiesLauncher</JAVA_MAIN_CLASS>
				       <JAVA_OPTIONS>-Dloader.main=com.redhat.quickstarts.fuse.sap_idoc_destination_spring_boot.Application</JAVA_OPTIONS>
                                    </env>
                                </controller>
                            </resources>
			    <images>
                                <image>
                                    <name>camel/actuator-http-metric</name>
                                    <build>
                                        <from>quay.io/jkube/jkube-java:0.0.19</from>
                                        <assembly>
                                            <mode>dir</mode>
                                            <targetDir>/deployments</targetDir>
                                            <layers>
                                                <layer>
                                                    <id>lib</id>
                                                    <fileSets>
						    <fileSet>
							<directory>${project.basedir}</directory>
							<outputDirectory>.</outputDirectory>
							<fileMode>0640</fileMode>
							<includes>classpath</includes>
                                                        </fileSet>
                                                        <fileSet>
							<directory>${project.basedir}/lib</directory>
							<outputDirectory>lib</outputDirectory>
							<fileMode>0640</fileMode>
                                                        </fileSet>
                                                    </fileSets>
                                                </layer>
                                            </layers>
                                        </assembly>
                                        <ports>
                                          <port>8080</port>
                                        </ports>
                                    </build>
                                </image>
                            </images>
		       </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>resource</goal>
                                    <goal>build</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

```

**Comment by cunningt** [comment]
Added a PR for openshift : https://github.com/jboss-fuse/sap-quickstarts/pull/15

**Comment by Croway** [comment]
this is great @cunningt , can I close this PR then? I'll handle the local execution with the testsuite

**Comment by cunningt** [comment]
@Croway I think we solved this - closing this out would be good

**Pull request closed without merging**
